import express, { Response, Request } from "express";
const authRouter = express.Router();
import { validateRequest } from "../middleware/zodMiddleware";
import { loginInSchema, signUpSchema } from "../models/auth";
import { authenticateUser } from "../middleware/middleware";
import logger from "../config/logger";
import { fetchUser, fetchUserName, forgotPass, login, signUp } from "../controllers/authController";
authRouter.post("/signup", validateRequest(signUpSchema), signUp);
authRouter.post("/login", validateRequest(loginInSchema), login);
authRouter.put("/forgot-pass", validateRequest(loginInSchema), forgotPass);
authRouter.get("/fetch-user", authenticateUser, fetchUser);
authRouter.get("/fetch-user-name", authenticateUser, fetchUserName);
export default authRouter;